spring:
  redis:
    host: localhost
    port: 6379
    password:

cache:
  lock:
    maxRetry: 3
    sleepTime: 200
    waitTime: 1
    leaseTime: 30

prefix:
  demo: demo_
  lock: lock_
  article: article_
